name: Docker CI Pipeline
run-name: ${{ github.actor }} is running on Docker CI Pipeline
on : [push]
  
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
     issues: write
     contents: read
     security-events: write
      
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run hadolint for dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
        with:
          dockerfile: Dockerfile
          ignore: DL4000

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@9adf32b1121593767fc3c057af55b55db032dc04
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@3c58388149901b9a03b7718852c5ba889646c27c
        with:
          target: 'https://ginandjuice.shop/'   #replace with alternate URL until app is live
          cmd_options: "-a"
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-report
          path: ./zap-full-scan-report.html

      - name: Docker Build
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1 .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
         username: ${{ vars.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1 

      - name: Run the container
        run: docker run --name helloworld-python -idt -p 8080:8080 ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1 

      - name: View the container
        run: docker ps
    
  K8s-implementation:
        needs: docker-build-push
        runs-on: ubuntu-latest
        steps:
        - name: Clone the code
          uses: actions/checkout@v6 
       
        - name: start minikube
          uses: medyagh/setup-minikube@e9e035a86bbc3caea26a450bd4dbf9d0c453682e
          
        - name: kubectl
          run: kubectl get pods -A
          
        - name: Deploy to minikube
          run: |
            kubectl apply -f manifests/deployment.yaml
            kubectl apply -f manifests/service.yaml
            kubectl wait --for=condition=ready pod -l app=hello-world-python
          
        - name: check deployments and service
          run: | 
           kubectl get deployments
           kubectl get service
         
        - name: check service URLs
          run: |
           minikube service list
           minikube service my-service --url
           echo "-----opening the service-----"
           curl $(minikube service my-service --url)
